plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Metrics/MethodLength:
  Max: 20

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10
